### PR TITLE
add flag for custom app path

### PR DESCRIPTION
**Pull request by willemml**
I wanted to use this while having nix home-manager manager my Spotify install, this means that Spotify is not installed in the usual location.

This PR simply adds a flag `-a` that allows a user to specify the path of the Spotify app.

### CODE REVIEW

**Review by Nuzair46 — CHANGES_REQUESTED** [review]
@willemml 
- [ ] Also add instructions for this change in the readme.
- [ ] Handle the same case for uninstallation

**Comment by jetfir3** [comment]
@willemml 
we have this option in the Linux version -- I would prefer the flags to match in both repos. 
`-P` flag is used to set PATH. Keeping lowercase a open for potential future features is ideal. 
https://github.com/SpotX-CLI/SpotX-Linux/blob/main/install.sh#L25

**Comment by willemml** [comment]
Thanks for the feedback! I'm working on the implementation for the uninstall script, should I add a flag getopt loop to it as well?

**Comment by jetfir3** [comment]
> should I add a flag getopt loop to it as well?

Would this be to loop around instead of `exit`ing if unknown/incorrect flag is used.. or?

**Comment by willemml** [comment]
I just looked at the Linux uninstall script and it would be exactly the same thing (looping through reach flag).

**Comment by jetfir3** [comment]
Looks good.

**Pull request merged**
